### ISSUE TITLE
Access issue

### ISSUE THREAD

**Issue by DorianRollin** [YUYING07/iDNA-ABF-automl#2]
Hi,

I have 2 questions : 

1. The "One Drive" that you shared is, sadly, no longer available. Can you make it accessible again?

2. When I tried to run the `train_ABF.py` file I had the current error : 
```
Traceback (most recent call last):
  File "/nfs/wsi/ab/projects/dorian/MuLan_comparison/iDNA-ABF-automl/main/train_ABF.py", line 14, in <module>
    from module.lightning_data_module import SeqDataModule
  File "/nfs/wsi/ab/projects/dorian/MuLan_comparison/iDNA-ABF-automl/module/lightning_data_module.py", line 7, in <module>
    from model import Pretrain_Feature_Extractor
ImportError: cannot import name 'Pretrain_Feature_Extractor' from 'model' (unknown location)
``` 

And indeed, there isn't anything with the name `Pretrain_Feature_Extractor` in the `model` folder, is it a model that we have to provide?
Same question for `TextCNN` for line 9 of `lightning_frame_module.py` .

**Comment by YUYING07** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已经收到您的邮件~欢迎下次再邮~
